### PR TITLE
packages: added nss-pam-ldapd to test packages.

### PR DESCRIPTION
**Pull request by sidecontrol**

### CODE REVIEW

**Comment by pbrezina** [comment]
Hi, also add it to Debian please.

**Comment by sidecontrol** [comment]
Done.

**Review by pbrezina — COMMENTED** [review]
I think we also need pam_ldap for ubuntu and debian, right? Or does it come with nslcd?

**Comment by sidecontrol** [comment]
I just tested it, both libpam-ldapd and libnss-lapd come with nslcd. Changed it so it just contains nslcd.

**Review by ikerexxe — APPROVED** [review]
LGTM! Rebase on top of master so that this can be merged.

**Pull request merged**
