### PR TITLE
Rename env.example to .env.example

### PR DESCRIPTION
**Pull request by ikerexxe**

### CODE REVIEW

**Comment by pbrezina** [comment]
My opinion is that example files should not be hidden so they are visible. What is the intention to hide it? Is it only to have the same name as the `.env` file?

**Comment by pbrezina** [comment]
If yes, I would rather prefer to fix the readme file to `cp env.example .env` instead.

**Comment by ikerexxe** [comment]
I was trying to be consistent with the documentation, where there are several references to `.env.example`. The proposed change was easier to perform, but I don't mind reverting this change and changing the documentation instead (`.env.example` -> `env.example`).

**Comment by pbrezina** [comment]
Please, update the documentation instead. I believe it is better to leave example file visible.

**Review by pbrezina — APPROVED** [review]

**Pull request merged**
