### PR TITLE
compose file improvements

### PR DESCRIPTION
**Pull request by pbrezina**

### CODE REVIEW

**Review by ikerexxe — COMMENTED** [review]
Did you forget to add the `security_opt` configuration for the ldap container or is it intentional?

**Comment by pbrezina** [comment]
> Did you forget to add the `security_opt` configuration for the ldap container or is it intentional?

Yes.

PR was updated. I added also few additional patches.

**Comment by pbrezina** [comment]
Fixed.

**Review by ikerexxe — APPROVED** [review]
LGTM. Good work!

**Pull request merged**
