### PR TITLE
provision: move random.so into standalone rpm

### PR DESCRIPTION
**Pull request by pbrezina**
To avoid pulling in build dependencies in minimal testing environment.

### CODE REVIEW

**Review by ikerexxe — APPROVED** [review]
I was also thinking about doing something similar, but my idea was to move the code to a separate repository and let COPR build it when the repository changed.

In any case, this is an improvement from the current workflow so I'm approving it.

**Comment by ikerexxe** [comment]
> It is actually built in copr and it will be rebuilt on any change. https://copr.fedorainfracloud.org/coprs/g/sssd/ci-deps/monitor/

I had a different idea to reach to the same point :rofl:

**Comment by pbrezina** [comment]
Rebased on top of Jakub's changes.

**Comment by ikerexxe** [comment]
Pavel you'll need to rebase this PR due to https://github.com/SSSD/sssd-ci-containers/pull/54

**Comment by pbrezina** [comment]
Rebased.

**Review by ikerexxe — APPROVED** [review]

**Review by jakub-vavra-cz — APPROVED** [review]
The ansible parts look good. I can't really comment on the rpm/copr side of things as I am not familiar enough with that.

**Pull request merged**
