### PR TITLE
Packages: install 'acl' to get 'setfacl'

### PR DESCRIPTION
**Pull request by alexey-tikhonov**

### CODE REVIEW

**Comment by alexey-tikhonov** [comment]
I'd like to (try to) use `setfacl` in 'passkey' tests.

**Comment by ikerexxe** [comment]
Given that we are installing this package for the passkey tests, can you move it to the [passkey dependencies installation section](https://github.com/SSSD/sssd-ci-containers/blob/master/src/ansible/roles/packages/tasks/Fedora.yml#L192)?

**Comment by alexey-tikhonov** [comment]
> Given that we are installing this package for the passkey tests, can you move it to the [passkey dependencies installation section](https://github.com/SSSD/sssd-ci-containers/blob/master/src/ansible/roles/packages/tasks/Fedora.yml#L192)?

Done.

**Review by ikerexxe — APPROVED** [review]
LGTM!

**Pull request merged**
